### ISSUE TITLE
react-trebuchet branch routing is unreliable

### ISSUE THREAD

**Issue by jforaker** [barrystaes/react-trebuchet#14]
Programatic routing is extremely brittle with the trebuchet version and react-router imo and needs to be upgraded.  After hours of fiddling with it I realized it was running an old version. Most cases programatic routing flat out didnt work.

Should be able to do this (http://stackoverflow.com/a/34863577/1516309):

```
import { browserHistory } from './react-router'
browserHistory.push('/some/path')
```

I'm not sure the status of that branch but it caused a lot of headache in getting trivial routing up and running. Maybe should review.

**Comment by barrystaes** [comment]
Well the status of the branch right now is mostly experimental / testing .. but the aim is to get this to reference implementation levels ultimately.

What versions did you have to update to?
Has this to do with [this commit](https://github.com/reactjs/react-router-redux/commit/204ab3dd77b74a61097cc40380ab4407e766d72c) in `react-router-redux`? 

But i expected routing to work fine, thanks for mentioning that!
I'd be happy to accept your PR.

**Comment by barrystaes** [comment]
In the latest `react-trebuchet` v0.1.9  i updated the router packages, updated the code and added an example.

**Comment by jforaker** [comment]
Thanks Barry - I actually ended up ditching `react-router-redux` for my project all together and just updated react-router so i could use the new `this.context.router.push('/whatever');` methods.. Thanks for the great boilerplate :+1:
